### ISSUE TITLE
Make sure that phrozn is installable when PEAR is run form user's dir

### ISSUE THREAD

**Issue by farazdagi** [Pawka/phrozn#19]
From chatlog:

srsly, is there no way of installing phrozn using pear without being root?
I've tried installing pear to my home dir (using debian) with no problems, and installing phrozn into that dir, but phr gives me a lot of wierd errors are the lib paths hard coded?

**Comment by jeremymturner** [comment]
I was able to install PEAR and Phrozn as a non-root user on Dreamhost's shared web space.

This link is a good reference: http://wiki.dreamhost.com/PEAR#Installing_Packages

I had to modify ~/pear/phr and ~/pear/phrozn to include 'php/Phrozn/Autoload.php' instead of Phrozn/Autoload.php. Also, I had to add the following section:

set_include_path(
    get_include_path() . 
    PATH_SEPARATOR . '/home/(username)/pear/php'
);

Worked great after that.

Jeremy

**Comment by Pawka** [comment]
Maybe it would be good idea add Console_CommandLine and Console_Color to vendors dir? Then Phrozn could be used instantly just by fetching code from Github.

**Comment by Pawka** [comment]
Related #59 and #60. After switch to Composer, installation via pear will not be required.

**Comment by Pawka** [comment]
Not actual anymore after #60 was merged.

**Comment by farazdagi** [comment]
@Pawka Yep, Composer as such supports installation into custom directory. Here is [updated installation instructions](http://www.phrozn.info/en/installation/#composer).
