### ISSUE TITLE
Default folder ./phrozn , problem for IDE

### ISSUE THREAD

**Issue by icomefromthenet** [Pawka/phrozn#5]
Using IDE like netbeans having the default dir as ./phrozn causes hidden directory in the file explorer.

Good to have the folder setting as a config option.

**Comment by farazdagi** [comment]
Agreed, will abstract the project folder, so that it is settable.

**Comment by treffynnon** [comment]
There are easier ways around this problem by configuring your IDE:
- http://mrhaki.blogspot.com/2008/06/display-hidden-dot-files-and.html
- https://www.codemagi.com/blog/post/195

**Comment by farazdagi** [comment]
Tend to agree with Simon - it is easier to configure the IDE.

However, the argument of having the project folder somewhere besides `.phrozn` is still valid (and actually all the abstractions for such shift are in place, for eg: project path is abstracted as [Phrozn\Path\Project](https://github.com/farazdagi/phrozn/blob/master/Phrozn/Path/Project.php) object, so that refactoring shouldn't be that much of an issue).

**Comment by trq** [comment]
I very much agree that you should be able to configure your project path and indeed phr up's SRC argument should accept this directory.

Currently I have something like:

```
project/
  src/.phrozn
  htdocs/
```

The src directory is a git repo containing the source for my site, while htdocs is a symlink to an apache vhost where the site resides. This is built using....

```
phr up src htdocs
```

It seems silly that my git repo should contain a single .phrozn directory with my source in it.

**Comment by farazdagi** [comment]
This issue should be resolve now. Thanks @wdalmut for PR.
